service: testLiteThinking

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  - ${file(config/company.lambda.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    # include
    - src/**
    - config/**
    # exclude
    - '!__tests__/**'
    - '!node_modules/**'


















































