list:
  handler: src\handlers\company\crud\list.handler
  events:
    - http:
        path: companies
        method: get

create:
  handler: src\handlers\company\crud\create.handler
  events:
    - http:
        path: companies
        method: post