register:
  handler: src/handlers/users/register.handler
  events:
    - http:
        path: register
        method: post
        cors: true

login:
  handler: src/handlers/users/login.handler
  events:
    - http:
        path: login
        method: post
        cors: true